### ISSUE TITLE
Problem running alexa-tv.py

### ISSUE THREAD

**Issue by ElDoctero** [efpe/amazon-alexa-lg-tv#3]
Everything else works fine, set my TV's mac address, however when I run the final command

C:\Projects\lgtv>python alexa-tv.py
Traceback (most recent call last):
  File "alexa-tv.py", line 47, in <module>
    p = fauxmo.poller()
  File "C:\Projects\lgtv\fauxmo.py", line 67, in __init__
    self.poller = select.poll()
AttributeError: 'module' object has no attribute 'poll'

I get that error. Not a python guy, so any help would be appreciated.

**Comment by efpe** [comment]
That because poll is not supported on non-unix based machines.

https://docs.python.org/2/library/select.html#poll-objects
