### ISSUE TITLE
Alexa Skill?

### ISSUE THREAD

**Issue by oxhey** [efpe/amazon-alexa-lg-tv#6]
Do I need to create or enable a new Alexa skill for this to work?

Also are any other commands supported other than on/off?

**Comment by khiles** [comment]
I have to admit a guide would be nice

**Comment by oxhey** [comment]
I think this is acting like a light and therefore can only do on/off.

**Comment by efpe** [comment]
No, it is only for on/off. However, there is a PR which enabled other functionality. See the code: https://github.com/efpe/amazon-alexa-lg-tv/pull/8

You can get the code from his repo until it's merged.
